# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Topic.create!(title: "Best")

facts = [
{topic_id: 1, quote: "He gave his father 'the talk'."},
{topic_id: 1, quote: "His passport requires no photograph."},
{topic_id: 1, quote: "He never says something tastes like chicken.. not even chicken."},
{topic_id: 1, quote: "Superman has pijamas with his logo."},
{topic_id: 1, quote: "His tears can cure cancer, too bad he never cries."},
{topic_id: 1, quote: " He can speak Russian… in French."},
{topic_id: 1, quote: "If he were to punch you in the face you would have to fight off a strong urge to thank him."},
{topic_id: 1, quote: "He once went to the psychic, to warn her."},
{topic_id: 1, quote: "His feet don’t get blisters, but his shoes do."},
{topic_id: 1, quote: "His Cinco de Mayo party starts on the 8th of March."},
{topic_id: 1, quote: "Once a rattlesnake bit him, after 5 days of excruciating pain, the snake finally died."},
{topic_id: 1, quote: "When he drives a car off the lot, its price increases in value."},
{topic_id: 1, quote: "He once brought a knife to a gunfight… just to even the odds."},
{topic_id: 1, quote: "When he meets the Pope, the Pope kisses his ring."},
{topic_id: 1, quote: "Bear hugs are what he gives bears."},
{topic_id: 1, quote: "The circus ran away to join him."},
{topic_id: 1, quote: "His friends call him by his name, his enemies don’t call him anything because they are all dead."},
{topic_id: 1, quote: "He has never waited 15 minutes after finishing a meal before returning to the pool."},
{topic_id: 1, quote: "If he were to visit the dark side of the moon, it wouldn’t be dark."},
{topic_id: 1, quote: "He once won a staring contest with his own reflection."},
{topic_id: 1, quote: "He can kill two stones with one bird."},
{topic_id: 1, quote: "His signature won a Pulitzer."},
{topic_id: 1, quote: "When a tree falls in a forest and no one is there, he hears it"},
{topic_id: 1, quote: "He once got pulled over for speeding, and the cop got the ticket."},
{topic_id: 1, quote: "The dark is afraid of him."},
{topic_id: 1, quote: "Sharks have a week dedicated to him."},
{topic_id: 1, quote: "His ten gallon hat holds twenty gallons."},
{topic_id: 1, quote: "No less than 25 Mexican folk songs have been written about his beard."},
{topic_id: 1, quote: "He once made a weeping willow laugh."},
{topic_id: 1, quote: "He lives vicariously through himself."},
{topic_id: 1, quote: "His business card simply says ‘I’ll Call You.'"},
{topic_id: 1, quote: "He once taught a German shepherd how to bark in Spanish"},
{topic_id: 1, quote: "He bowls overhand."},
{topic_id: 1, quote: "In museums, he is allowed to touch the art"},
{topic_id: 1, quote: "He is allowed to talk about fight club.."},
{topic_id: 1, quote: "He once won a fist fight, only using his beard."},
{topic_id: 1, quote: "He once won the Tour-de-France, but was disqualified for riding a unicycle."},
{topic_id: 1, quote: "A bird in his hand is worth three in the bush."},
{topic_id: 1, quote: "His lovemaking has been detected by a seismograph."},
{topic_id: 1, quote: "The Holy Grail is looking for him."},
{topic_id: 1, quote: "Roses stop to smell him."},
{topic_id: 1, quote: "He once started a fire using only dental floss and water."},
{topic_id: 1, quote: "His sweat is the cure for the common cold."},
{topic_id: 1, quote: "Bigfoot tries to get pictures of him."},
{topic_id: 1, quote: "Werewolves are jealous of his beard."},
{topic_id: 1, quote: "He once turned a vampire into a vegetaria.n"},
{topic_id: 1, quote: "He once won the world series of poker using UNO cards."},
{topic_id: 1, quote: "He never wears a watch because time is always on his side."},
{topic_id: 1, quote: "He has taught old dogs a variety of new tricks."},
{topic_id: 1, quote: "He has won the lifetime achievement award… twice."},
{topic_id: 1, quote: "If opportunity knocks, and he’s not at home, opportunity waits."},
{topic_id: 1, quote: "Batman watches Saturday morning cartoons about him."},
{topic_id: 1, quote: "When he was young he once sent his parents to his room."},
{topic_id: 1, quote: "He once had an awkward moment, just to see how it feels."},
{topic_id: 1, quote: "His beard alone has experienced more },han a lesser man’s entire body."},
{topic_id: 1, quote: "His blood smells like cologne."},
{topic_id: 1, quote: "On every continent in the world, there is a sandwich named after him."},
{topic_id: 1, quote: "Mosquitoes refuse to bite him purely out of respect."},
{topic_id: 1, quote: "He is fluent in all languages, including three that he only speaks."},
{topic_id: 1, quote: "Once while sailing around the world, he discovered a short cut."},
{topic_id: 1, quote: "Panhandlers give him money."},
{topic_id: 1, quote: "When he goes to Spain, he chases the bulls."},
{topic_id: 1, quote: "His shadow has been on the ‘best dressed’ list twice."},
{topic_id: 1, quote: "When he holds a lady’s purse, he looks manly."},
{topic_id: 1, quote: "Two countries went to war to dispute HIS nationality."},
{topic_id: 1, quote: "When in Rome, they do as HE does."},
{topic_id: 1, quote: "His pillow is cool on BOTH sides."},
{topic_id: 1, quote: "The Nobel Academy was awarded a prize from HIM."},
{topic_id: 1, quote: "He taught Chuck Norris martial arts."},
{topic_id: 1, quote: "Time waits on no one, but him."},
{topic_id: 1, quote: "Once he ran a marathon because it was “on the way”."},
{topic_id: 1, quote: "His mother has a tattoo that says “Son”."},
{topic_id: 1, quote: "The star on his Christmas tree is tracked by NASA."},
{topic_id: 1, quote: "Presidents take his birthday off."},
{topic_id: 1, quote: "His shirts never wrinkle."},
{topic_id: 1, quote: "He has never walked into a spider web."},
{topic_id: 1, quote: "He is left-handed. And right-handed."},
{topic_id: 1, quote: "His shirts never wrinkle."},
{topic_id: 1, quote: "The police often question him, just because they find him interesting."},
{topic_id: 1, quote: "His organ donation card also lists his beard."},
{topic_id: 1, quote: "He doesn’t believe in using oven mitts, nor potholders."},
{topic_id: 1, quote: "His cereal never gets soggy. It sits there, staying crispy, just for him"},
{topic_id: 1, quote: "Respected archaeologists fight over his discarded apple cores"},
{topic_id: 1, quote: "His garden maze is responsible for more missing persons than the bermuda triangle"},
{topic_id: 1, quote: "If he were to say something costs an arm and a leg, it would"},
{topic_id: 1, quote: "He’s never lost a game of chance."},
{topic_id: 1, quote: "He is the life of parties that he has never attended."},
{topic_id: 1, quote: "He once caught the Loch Ness Monster...with a cane pole, but threw it back."},
{topic_id: 1, quote: "His wallet is woven out of chupacabra leather"},
{topic_id: 1, quote: "He played a game of Russian Roulette with a fully loaded magnum, and won."},
{topic_id: 1, quote: "Freemasons strive to learn HIS secret handshake."},
{topic_id: 1, quote: "If he was to pat you on the back, you would list it on your resume."},
{topic_id: 1, quote: "He is considered a national treasure in countries he’s never visited."},
{topic_id: 1, quote: "Cars look both ways for him, before driving down a street."},
{topic_id: 1, quote: "He once tried to acquire a cold just to see what it felt like, but it didn’t take."},
{topic_id: 1, quote: "He has inside jokes with people he’s never met."},
{topic_id: 1, quote: "He has never filled up on chips."},
{topic_id: 1, quote: "Bikers walk their motorcycles past his home."},
{topic_id: 1, quote: "He has inside jokes with complete strangers."}]

facts.each do |f|
  Fact.create!(f)
end
